# Site settings
title: Homepage of Dr. Samuel Jones
email: samuel.jones@h-its.org
#description: > # this means to ignore newlines until "baseurl:"
#  Thank you for visiting my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: Samisthebest
github_username:  swjones

# Build settings
markdown: kramdown
maruku:
  use_tex:    true

