# Site settings
title: Samuel Jones
email: swjones at lanl.gov
#description: > # this means to ignore newlines until "baseurl:"
#  Thank you for visiting my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: Samisthebest
github_username:  swjones

# Build settings
markdown: kramdown
maruku:
  use_tex:    true

